### ISSUE TITLE
Migration to pydantic v2 (and pydantic-settings)

### ISSUE THREAD

**Issue by JakobKristoffersenATP** [dudil/fastapi_msal#27]
Thank you for this package! We are currently migrating to pydantic v2 and are having issues with the current version of the package which has a strict dependency to `pydantic=1.*`.

I propose we migrate to `pydantic=2.*` and  `pydantic-settings` for `BaseSettings` (for`MSALClientConfig`). 

Alternatively only migrate to `pydantic-settings` for usage of `BaseSettings` and loosen up the `pydantic=1.*` dependency,

**Comment by dudil** [comment]
Hi @JakobKristoffersenATP  - I've migrated to pydantic version 2 with latest release 2.0
I've conduct some local test but I highly recommend you to perform your own testing to make sure nothing broken.

Good luck.
