### ISSUE TITLE
[Auth bug] 500 instead of 401 when invalid auth token (JWT) is provived

### ISSUE THREAD

**Issue by rmwesley** [dudil/fastapi_msal#30]
**Describe the bug**
Normally, authentication is done using OAuth2. If you're not properly authenticated and try to use the API, you'll receive a 401 Unauthorized response:

```
{
    "detail": "Not authenticated
}
```
This is expected behavior! Great.

But if you try to **authenticate with an invalid Bearer Token**, you get a 500 error instead of a 401, leaving the user in the dark as to the source of the problem, unless they check out the logs in detail.

**On JWTs**
Upon providing valid OAuth2 through a `POST` to `/oauth2/v2.0/token`, a valid Bearer Token is generated and sent back with a `200 OK` status :
https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/ 

As described, these are simply 3 sequences of alphanumeric characters separated by certain punctuation characters. Periods "." in our case:
https://www.oauth.com/oauth2-servers/access-tokens/self-encoded-access-tokens/ 

> This token is made up of three components, separated by periods. The first part describes the signature method used. The second part contains the token data. The third part is the signature.

Here is the example provided by https://oauth.com:
`
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2F1dGhvcml6YXRpb24tc2VydmVyLmNvbS8iLCJleHAiOjE2MzczNDQ1NzIsImF1ZCI6ImFwaTovL2RlZmF1bHQiLCJzdWIiOiIxMDAwIiwiY2xpZW50X2lkIjoiaHR0cHM6Ly9leGFtcGxlLWFwcC5jb20iLCJpYXQiOjE2MzczMzczNzIsImp0aSI6IjE2MzczMzczNzIuMjA1MS42MjBmNWEzZGMwZWJhYTA5NzMxMiIsInNjb3BlIjoicmVhZCB3cml0ZSJ9.SKDO_Gu96WeHkR_Tv0d8gFQN1SEdpN8S_h0IJQyl_5syvpIRA5wno0VDFi34k5jbnaY5WHn6Y912IOmg6tMO91KlYOU1MNdVhHUoPoNUzYtl_nNab7Ywe29kxgrekm-67ZInDI8RHbSkL7Z_N9eZz_J8c3EolcsoIf-Dd5n9y_
`

Important data is encoded on the middle value (user identification, scope of authorization...). You can change the first (signature method) and last (signature itself) parts of the JWT while keeping the dots, and you'll still be authenticated by MSAL. Is this expected behavior? The JWT needs to be validated, look into the **Validate the signature** section:
https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens

This issue seems to be related:
https://github.com/dudil/fastapi_msal/pull/17

Now to the issues
**To Reproduce**
The internal errors are caused by raised runtime errors in the running Python code. Most of them are related to `oauth2cli`.

**If you play around with the JWT sent in the authorization header as a Bearer Token by changing its data you can raise many different errors.** These mostly can be traced back to the `json.loads(decode_part(id_token.split('.')[1]))` code that converts the JWT to a JSON object in Python.
- `IndexError`  if you remove the separator/delimiter dots "." and send only alphanumerical characters. Raised by `id_token.split('.')[1]`.
- `UnicodeDecodeError` if you provide invalid `Base64` data in the middle part of the token. Raised by the native Python string `decode()` function.
- `decoder.JSONDecodeError` if you provide valid Base64 but it translates to invalid JSON. Raised by the json package decoder.
- `RuntimeError` if JWT content is in proper JSON format but still invalid (expired or similar).

Etc.

**Expected behavior**
These raised errors are expected. They are not the issue. The problem is sending a 500 instead of a 401.
The 401 response only occurs if the JWT is empty/not sent.

I believe the fix here is to wrap these runtime errors in a try/catch block and raise an HTTP error instead, so that the controller or similar receives back the raised error and finally responds to the client's HTTP request with a 401 when Unauthentified instead of 500.
Like in this PR by [yaokaibb](https://github.com/yaokaibb) (We think alike! Haha): https://github.com/dudil/fastapi_msal/pull/21

*To be filled later*
**Environment Settings**
- OS: [Linux/Mac/Windows]
- Python Version: [NB! Only version 3.9+ is currently supported]
- Packages Versions: [masl / fastapi / fastapi_msal]

**Comment by rmwesley** [comment]
Here's an open discussion on FastAPI that may be related to this subject:
https://github.com/tiangolo/fastapi/discussions/10615
This discussion is related to a 500 **upon trying to authenticate**, which is not the same issue as here.
In this case (trying to authenticate) we should get a 400 for invalid credentials (Bad request). Should I open another issue here for this Swagger UI bug?

In our case we should get a 401, since **we are not trying to authenticate**, we are trying to **use the API with an invalid Bearer Token**.

**Comment by dudil** [comment]
Hi @rmwesley - thank you for that very much detailed description.
The issue is clear and for some reason missed that before.
I made the change and will publish it upon the next version 🙏

**Comment by rmwesley** [comment]
By the way, this issue is still open:
https://github.com/dudil/fastapi_msal/issues/10

It is related to https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/473 as [ejsyx](https://github.com/ejsyx) said, right?
As seen in the discussion, **MSAL does not use PyJWT's decode function for decoding JWTs**, only for encoding them.

So MSAL decodes the JWT with their own custom-made `decode_id_token()` function in `oauth2cli/oidc.py`, right ? Or am I totally lost, mixing things up?

This function only decodes the middle part of the token (with `decode_part(id_token.split('.')[1])`), completely ignoring the signature validation.
Again, as seen on [Access tokens](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens). [fbelhadi](https://github.com/fbelhadi) also mentioned this page comparing it to [ID tokens](https://learn.microsoft.com/en-us/entra/identity-platform/id-tokens).
https://github.com/dudil/fastapi_msal/pull/17 only mentions RBAC, but it aims to fix the concerns raised by [ejsyx](https://github.com/ejsyx) as well, then? The signature validation issue also? Or am I just making a crazy soup of unrelated issues?

**Comment by rmwesley** [comment]
Very good, thanks a lot for the reactivity!

I still wanted to comment on the [OIDC](https://learn.microsoft.com/en-us/entra/identity-platform/v2-protocols-oidc) code for OpendID Connect grant flow.

Apparently, all handling of issued `id_tokens` on Python MSAL's repo is done under [oauth2cli/oidc.py](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/oauth2cli/oidc.py). Correct me if I'm wrong and part of the grant flow is done somewhere else, it is not clear to me.

Most of the raised runtime errors I mentioned above are related to the decoding of the `id_token` JWT in the middle of the OIDC grant flow.


It may seem unrelated, but I stumbled upon [this issue](https://github.com/dudil/fastapi_msal/issues/10) that is still open here.

As [ejsyx](https://github.com/ejsyx) said regarding JWT decoding, **MSAL does not use PyJWT's decode function for decoding JWTs**, only for encoding them. This is based on what [rayluo](https://github.com/rayluo) commented on [this PyJWT decoding issue](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/473).

So MSAL decodes the `id_token` JWT with their own custom-made `decode_id_token()` function in [oauth2cli/oidc.py](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/msal/oauth2cli/oidc.py), right? 
 
This function only decodes the middle part of the `id_token`, since under `oauth2cli/oidc.py` MSAL uses a custom `decode_part(id_token.split('.')[1])` function, and thus it completely ignores the signature validation, as I mentioned in my original post.

But besides that, OIDC grant flow, that issues an `id_token`, should not be used for authentication. For auth, [an auth code flow is supposed to be done](https://auth0.com/blog/id-token-access-token-what-is-the-difference/), issuing an `access_toke` as a grant. [fbelhadi](https://github.com/fbelhadi) mentioned this issue on [this PR](https://github.com/dudil/fastapi_msal/pull/17) arguing [Access tokens](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens) should be used instead of [ID tokens](https://learn.microsoft.com/en-us/entra/identity-platform/id-tokens). There he mentions the MIP docs I refer to in my posts haha.

[This pull request](https://github.com/dudil/fastapi_msal/pull/17) only mentions RBAC, but does it aim to fix the concerns raised by [ejsyx](https://github.com/ejsyx) as well, or not at all? I mean, if you switch the grant flow and end up with an `access_token` instead the signature validation issue of `id_tokens` will become obsolete, right? Or am I just making a crazy soup of unrelated issues?

**Comment by dudil** [comment]
De nada @rmwesley 
As this issue is now marked as closed I propose to open few new ones.
It seems to me like you are referring to different topics so can you make sure each has its own topic?
Will help me to better answer them.
The first is about the MSAL JWT token, I will look into that once I can better understand the issue / concern.
The second is about updating the documentations which are long past due... probably my next challenge here 😅 
The third is about the RBAC which while the PR is simple I'm not sure if that the correct implementation to handle that issue.
We can discuss and I'll elaborate more on that ticket if this is making more sense.

Obrigado 🙏

**Comment by rmwesley** [comment]
Tranquilo kkkk
I was just noting down some things I was analysing, I rewrote this message at least three times to try and make it make sense, I will keep rewriting it for a while haha. Also, the "MIP" docs I mentioned are those of Microsoft Identity platform I keep referring to: [Access tokens](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens) and [ID tokens](https://learn.microsoft.com/en-us/entra/identity-platform/id-tokens).
