### ISSUE TITLE
Route to token_path is http when I need httpS per Azure application configuration

### ISSUE THREAD

**Issue by reckoner** [dudil/fastapi_msal#31]
**Is your feature request related to a problem? Please describe.**

I can get everything to work on local where the token_path is http to localhost but my Azure
app needs to route to https. I don't know how to specify https fo the token_path

**Describe the solution you'd like**

I need to get the token_path to use https somehow. I don't see where that would happen in the code

**Describe alternatives you've considered**

I'm using FastAPI but I can't find an option in there that'll do this https.

**Additional context**

**Comment by dudil** [comment]
Hello @reckoner, HTTP vs. HTTPS is the web server configuration not relevant to the actual app code.
In the case of local development most chances you are using [uvicorn](https://www.uvicorn.org).
In azure (AKA stage/production) you should use a reverse proxy for HTTPS termination. 
There is a full chapter around the concept in the FastAPI documentation (Which is brilliant as always 😊):

[https://fastapi.tiangolo.com/deployment/concepts/](https://fastapi.tiangolo.com/deployment/concepts/)

I hope you will find that helpful and thank you for using fastapi_msal 😄

**Comment by reckoner** [comment]
Thanks for all your great work!
