### ISSUE TITLE
Cannot use B2C logins

### ISSUE THREAD

**Issue by JohnCHarrington** [dudil/fastapi_msal#32]
**Describe the bug**
B2C login policy cannot be used as the authority is an empty string. It seems like `core.msal_client_config.py` line 59 which is currently `elif self.policy not in {` should actually be `elif self.policy in {` ?

I am currently using this effectively by overwriting the authority property with the correct URL

**To Reproduce**
Set up with B2C login, set `policy` to `MSALPolicies.B2C_LOGIN`

**Expected behavior**
Correct authority should be set, ` f"https://{self.tenant}.b2clogin.com/{self.tenant}.onmicrosoft.com/{self.policy}"`

**Environment Settings**
- OS: Linux
- Python Version: 3.11
- Packages Versions: [msal: 1.27.0 / fastapi:  0.109.2 / fastapi_msal: 2.1.2]

**Comment by dudil** [comment]
Thank you @JohnCHarrington - very interesting finding.
Seems like I did a mistake by mixing policies (which seems to be relevant only for B2C) and authorities.
But to be honest, looking at the internal of the python MSAL, they are not even considering or providing a decent support for the B2C scenario... so 🤷‍♂️

Anyway, I need to think how to solve that mix as the two needs to be seperated but I would like to avoid a breaking change.

I'll issue a patch to resolve that for now, but if you have any idea for a more resilient change this would be very much welcome 🙏
