### ISSUE TITLE
Authority URL is now always returns as a b2c url.

### ISSUE THREAD

**Issue by timovp** [dudil/fastapi_msal#33]
**Describe the bug**
I have a `AAD_Single` app registration and application, therefore i need the authority URL for this particular MSALpolicy, however with the recent commit, it's now always returned with a b2c policy. 

**To Reproduce**
go to `core/msal_client_config,py` line 72. 

**Expected behavior**
I would have expected an early return when the authority url is set and not being overwritten by other if statements or at all. 

**Environment Settings**
- OS: WSL / Ubuntu20.04
- Python Version: 3.11
- Packages Versions: 
    - msal==1.27.0 
    - fastapi==0.110.0
    - fastapi_msal==2.1.3

**Additional context**
Adding the early returns solves the issue for my use case, but perhaps my understanding of the policy and b2cpolicy settings is not extensive enough have the full context for all.

**Comment by dudil** [comment]
Thanks @timovp 
Can you please write down the specific configuration you are using for the authority?

**Comment by timovp** [comment]
Sure, I actually didn't change anything from the example setup, just provided a tentant, client id and client credential. 
 ```python
class AppConfig(MSALClientConfig):
    """The application configuration class."""

    endpoint: str = "https://graph.microsoft.com/v1.0/users"
    login_path: str = "/login"
    logout_path: str = "/logout"
    path_prefix: str = "/auth"
    token_path: str = "/redirect"
    client_id: str = CLIENT_ID
    client_credential: str = CLIENT_CREDENTIAL
    tenant: str = TENANT
```

I would expect that my authority_url becomes: `"https://login.microsoftonline.com/{self.tenant}"`

**Comment by dudil** [comment]
Got you, might it be you have a .env file or a predefined environment variable which is setting the policy externally?
