### ISSUE TITLE
Missing "groups" property on IDTokenClaim

### ISSUE THREAD

**Issue by JakobKristoffersenATP** [dudil/fastapi_msal#36]
**Is your feature request related to a problem? Please describe.**
The `groups` property is missing on the `IDTokenClaims `model.  See current MS documentation: https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference 

**Describe the solution you'd like**
`groups `added as an optional field to the `IDTokenClaims` model.

**Describe alternatives you've considered**
I have locally made a quick fix by parsing the raw` _id_token` property. For future cases like this, it would also be nice if the decoded token would be added as a private attribute to the `IDTokenClaims `model similar to `_id_token`.

**Comment by JakobKristoffersenATP** [comment]
Hi @dudil,

Thank you for your quick reply.

> Can you please add more details or the code you've mentioned?
Per the the documentation you provided MS is usually won't send the groups but will ask you to read if from the graph API.
https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#groups-overage-claim

As I read the documentation, they recommend the client to only call graph API, if the overage limit for the token have been reached. So first look in the `groups`/`hasgroups` properties and then fallback to calling graph API. 

the `groups` property seems, however, to be defined weakly. In our case it returns `list[str]`, so perhaps the implementation type could be `Any` untill it can be better defined as such:

```
class IDTokenClaims(UserInfo, AADInternalClaims):  
    ....
    
    groups: Any = None
    """
    For token requests that aren't limited in length (see hasgroups) but still too large for the token, a link to the full groups list for the user is included. For JWTs as a distributed claim, for SAML as a new claim in place of the groups claim.

    Example JWT Value:
        "groups":"src1"
        "_claim_sources: "src1" : { "endpoint" : "https://graph.microsoft.com/v1.0/users/{userID}/getMemberObjects" }
    
    For more info, see Groups overage claim as https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#groups-overage-claim
    """
```

> As for the decoded token, are you referring for keeping the decoded json in [IDTokenClaims.decode_id_token method](https://github.com/dudil/fastapi_msal/blob/2164bb5c90acba8c9bd43c5c919dbff39117fcb5/fastapi_msal/models/id_token_claims.py#L200)?

Yes, exactly. It is useful for propeties not properly defined in the model, but I would say it more "nice-to-have" than anything else.

**Comment by dudil** [comment]
I totally agree with you.
"defined weakly" is to say the least on Microsoft documentations now days.
There were used to be something to look at, and learn from 😞 

I will start from the last point, when I've created this library I've added a dynamic property for saving the data received.
So AuthToken has a property called `_recieved`.
This should work out for you, if this helps for now: `auth_token._recieved["id_token_claims"]`

As for the groups, on my own projects I don't get them back probably since I'm not asking that in scope.
Could you let me know what is the scope you are using so I can try that for myself?

**Comment by JakobKristoffersenATP** [comment]
Hi @dudil 

To get groups included in the token, you will have to adjust the manifest in your app registration. See more here:
https://learn.microsoft.com/en-us/entra/identity/hybrid/connect/how-to-connect-fed-group-claims#configure-the-microsoft-entra-application-registration-for-group-attributes

Thank you. I will look into the `_received `property on the `AuhToken`

**Comment by JakobKristoffersenATP** [comment]
> @JakobKristoffersenATP - could you please assist by review the branch created and let me know if these changes are solving the mentioned issues? Few relevant changes: 1 - Added the groups claim, I'm not able to simulate having more than 150 groups by myself, so it is Union with str assuming this is same as mentioned above. 2 - I've also update the model config to include "extra" fields, so if you are adding more custom claims or these are updated by MS they will still be accessible for the developer by using the `__pydantic_extra__` attribute of the model. You can read about it [here](https://docs.pydantic.dev/latest/concepts/models/#extra-fields)

The changes looks good and solves my issues. With the "extra allowed" model config, it might actually not be necessary to also include the `_decoded_token` as all none-defined properties are now included in the model.
