### ISSUE TITLE
Is python 3.7 / 3.8 supported?

### ISSUE THREAD

**Issue by Ezhvsalate** [dudil/fastapi_msal#38]
**Describe the bug**
Is python 3.8 still supported? I see in documentation 3.7 and above, in  pyproject.toml I see >=3.9 https://github.com/dudil/fastapi_msal/blob/master/pyproject.toml#L10 

**To Reproduce**
Try installing package with poerty on python 3.8, version solving will fail as fastapi-msal depends on python 3.9+

**Comment by dudil** [comment]
Hi @Ezhvsalate,
Support for python > 3.9 was dropped since version 2 (support of pydantic 2).
I will update the documentations accordingly, thank you for letting me know.
