### ISSUE TITLE
Question: How to bypass MSAL authentication for unit testing?

### ISSUE THREAD

**Issue by esenseial** [dudil/fastapi_msal#4]
Are there any best practices to bypass MSAL authentication for unit testing?

I already tried to do so using `dependency_overrides` but I could not figure out how to make it work.

Greetings,
Michael

**Comment by dudil** [comment]
Hi Michael,

Could you please be more specific around what you are trying to achieve?
What exactly the scenario you are trying to test?
Is there any specific flow or API in mind you were looking for in the library?
Are you looking for a mockup api? or maybe a way to have a "silent" authentication to MSAL?

Would love to help once I know exactly what you are looking for.

Cheers,
@dudil

**Comment by dudil** [comment]
@esenseial - are you still require my assistance here? :smile:
