### ISSUE TITLE
Cache doesn't survive server restart

### ISSUE THREAD

**Issue by teotwaki** [dudil/fastapi_msal#40]
Hi,

First of all, thanks for a great library. You've saved me many grey hairs, I'm sure.

**Describe the bug**

As far as I can tell, the library currently has an [in-memory cache](https://github.com/dudil/fastapi_msal/blob/master/fastapi_msal/core/session_manager.py#L21), which [cannot be overridden](https://github.com/dudil/fastapi_msal/blob/master/fastapi_msal/core/session_manager.py#L46). It appears that [some work was done](https://github.com/dudil/fastapi_msal/blob/master/fastapi_msal/core/msal_client_config.py#L44) to prepare for using [multiple types of caches](https://github.com/dudil/fastapi_msal/blob/master/fastapi_msal/core/session_manager.py#L14), but this is not available as of yet.

I'm trying to run this using [Mangum](https://github.com/jordaneremieff/mangum) on AWS Lambda, and obviously having a single in-memory cache doesn't work. Every time the lambda gets garbage collected (roughly every 15 minutes), or anytime a user gets sent to a different lambda, the cache hit fails, and they are sent through the SSO redirects again. This is reproducible locally by restarting the server in between requests.

**To Reproduce**
1. Start a server that SSO authenticates a user
2. Perform multiple actions, each action is instantly executed (AuthToken is found and returned). `sid` remains constant.
3. Restart the server, ensure session key is maintained
4. Perform an action
5. The user is SSO authenticated again, new `sid` generated.

**Expected behavior**
The `sid` should be recognised so that we don't need to re-authenticate the user.

**Additional context**
If you can provide me with some guidance, I'm happy to implement and provide a PR.

**Comment by dudil** [comment]
Hi @teotwaki ,

Thank you for your interest and support at this work. Highly appreciated 🙏

Support for external cache was something I've initially planned to implement but I didn't. 

I'll be happy to get back to it and add it, please allow me some time for investigation (or better remember what my plans were at time) and I'll share it with you to see if this would fit your needs.

**Comment by teotwaki** [comment]
Hi @dudil, have you had any further thoughts on this?

I really would love to get your thoughts on how to implement this, and I can either contribute code (if you give me some guidance) or happy to discuss sponsorship if that fits your agenda better.

Thanks in advance,
