### ISSUE TITLE
Question: Cannot install fastapi_msal on Windows

### ISSUE THREAD

**Issue by Najib-Hoseini** [dudil/fastapi_msal#5]
I'm getting the following error messages when I try to pip install fastapi_msal:

ERROR: Could not find a version that satisfies the requirement fastapi_msal (from versions: none)
ERROR: No matching distribution found for fastapi_msal

**Comment by dudil** [comment]
Hello @Najib-Hoseini - Can you please confirm you are using python 3.9+?
I believe this might cause the issue you've mentioned.

**Comment by Najib-Hoseini** [comment]
Hi dudil, I'm using Python 3.7 - so that might be it! Will future releases focus only on 3.9 + or will you also add support for 3.7?

**Comment by dudil** [comment]
Hello @Najib-Hoseini  
Challenge accepted! :smile:
Made the required corrections and tests and it is now supports version 3.7 and above.
Please let me know if this works well for you buddy.

:rocket:

**Comment by Najib-Hoseini** [comment]
The installation worked like a charm! Thanks so much dudil !!!

**Comment by Najib-Hoseini** [comment]
The installation worked like a charm! Thanks so much dudil !!!
