### ISSUE TITLE
How do I get past this stage to get the access token?

### ISSUE THREAD

**Issue by krakshayrao** [dudil/fastapi_msal#6]
I'm very new to FastAPI and Python. It'd be great if I get some help here. I'm using Python 3.9. and I'm stuck at this this page.
![image](https://user-images.githubusercontent.com/58678566/129340244-d6c71df1-c98a-49a6-9798-6e6d6be460a5.png)

I'm not sure how to change the redirect URI in the code.  

And also can you please let me know how we can protect APIs using the access token generated using MSAL and also validate the access token? cuz I tried to access the API by changing the access token but still it worked. So I wanted to know how I can validate the access token before executing it. Thanks in advance.

**Comment by dudil** [comment]
Hi @krakshayrao 

I advise you will look into this example repository - you should find some answers there:
https://github.com/dudil/ms-identity-python-webapp
Make sure to look into the fastapi_msal branch

If you will still have open questions I'll be happy to address them 😄

**Comment by krakshayrao** [comment]
Thank you @dudil :)
